default:
  handlers:
    - sink: sys.stdout
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    - sink: "logs/warnings/{name}-{time:YYYY-MM-DD-HH-mm-ss}.log"
      rotation: "500 MB"
      retention: "10 days"
      compression: "zip"
      format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
  level: INFO

dev:
  handlers:
    - sink: sys.stdout
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  level: DEBUG

prod:
  handlers:
    - sink: "logs/warning/{name}-{time:YYYY-MM-DD-HH-mm-ss}.log"
      rotation: "500 MB"
      retention: "30 days"
      compression: "tar.gz"
      format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
  level: WARNING